(
"dlrruururlr",
[
"xxxxxxxxxxxxxxx",
"xx------xx-x--x",
"xxx----xg---x-x",
"xx----xx-x----x",
"x-x-----xx----x",
"x---x-x----x--x",
"x-x----x------x",
"xx----x-----x-x",
"x-----xx---x-xx",
"x-x-xxx-2-x---x",
"x--xxxx4x-----x",
"x-xx----------x",
"x----x-------xx",
"x-x--xx-------x",
"x--xxx--3x--xxx",
"x-x----1------x",
"xxxxxxxxxxxxxxx"
]
)
