(
"uuddrddlrrd",
[
"xxxxxxxxxxxxxx",
"x-----x----x-x",
"x-x------x---x",
"xx-----xx----x",
"x-----x-xx-xgx",
"x-x--x---x1x-x",
"x-xx---xxxx--x",
"x------------x",
"x-x---xxx-x--x",
"x-x-----xx---x",
"x---x--xx----x",
"xx-x--x------x",
"x--x--x-----xx",
"xx--x---xx-xxx",
"xx--xx--x----x",
"x---x--xx--xxx",
"xxxxxxxxxxxxxx"
]
)

[
"xxxxxxxxxxxxxx",
"x-----x----x-x",
"x-x------x---x",
"xx-----xx----x",
"x-----x-xx-xgx",
"x-x--x----1--x",
"x-xx---xxx---x",
"x------------x",
"x-x---xxx-x--x",
"x-x-----xx---x",
"x---x--xx----x",
"xx-x--x------x",
"x--x--x-----xx",
"xx--x---xx-xxx",
"xx--xx--x----x",
"x---x--xx--xxx",
"xxxxxxxxxxxxxx"
]
